#!/bin/sh

while read file
do
  case "$1" in
  "d")
	[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
  "w")
    genwall $file
  esac 
done
