#!/bin/sh

#setwall &
xwallpaper --zoom ~/.local/share/wallpaper.jpg &
xcompmgr &
xset r rate 300 50
unclutter &
dwmblocks &
dunst &
backlight_control 30 &
# exec dwm > /dev/null 2>&1
while type dwm > /dev/null ; do dwm && continue || break ; done
