#!/bin/sh

#setwall &
xwallpaper --zoom ~/.local/share/wallpaper.jpg &
xcompmgr &
xset r rate 300 50
xrandr -r 60.00
unclutter &
dwmblocks &
dunst &
backlight_control 20 &
# exec dwm > /dev/null 2>&1
while type dwm > /dev/null ; do dwm && continue || break ; done
