#!/bin/sh

slstatus &
setwall &
xcompmgr &
xset r rate 300 50
dunst &
sxhkd &
setxkbmap -option caps:swapescape
# exec dwm > /dev/null 2>&1 
while type dwm > /dev/null ; do dwm && continue || break ; done
$exec dwm
